# Travis-CI Build for Cronos
# see travis-ci.org for details

sudo: required
dist: trusty

language: csharp

matrix:
  include:
    - os: linux
      dotnet: 2.1.401
      mono: none
      script:
        - travis_retry dotnet restore Cronos.sln --disable-parallel;
        - dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:netcoreapp2.1;

    - os: osx
      dotnet: 2.1.401
      mono: none
      script:
        - travis_retry dotnet restore Cronos.sln --disable-parallel;
        - dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:netcoreapp2.1;

    - os: linux
      mono: latest
      install:
        - nuget restore Cronos.sln
        - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory testrunner
      script:
        - msbuild /p:Configuration=Release Cronos.sln
        - mono ./testrunner/xunit.runner.console.2.4.1/tools/net452/xunit.console.exe ./tests/Cronos.Tests/bin/Release/net452/Cronos.Tests.dll

    - os: osx
      mono: latest
      install:
        - nuget restore Cronos.sln
        - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory testrunner
      script:
        - msbuild /p:Configuration=Release Cronos.sln
        - mono ./testrunner/xunit.runner.console.2.4.1/tools/net452/xunit.console.exe ./tests/Cronos.Tests/bin/Release/net452/Cronos.Tests.dll
