# Travis-CI Build for Cronos
# see travis-ci.org for details

sudo: required
dist: trusty
dotnet: 1.0.1
mono: none

language: csharp

os: 
  - linux
  - osx
  
# Run the build script
script:
    travis_retry dotnet restore Cronos.sln --disable-parallel;
    dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:netcoreapp1.0;
    dotnet build benchmarks/Cronos.Benchmarks/Cronos.Benchmarks.csproj -c Release -f netcoreapp1.1
    dotnet benchmarks/Cronos.Benchmarks/bin/Release/netcoreapp1.1/Cronos.Benchmarks.dll
