# Travis-CI Build for Cronos
# see travis-ci.org for details

sudo: required
dist: trusty
mono: none
dotnet: 
  - 2.1.401
  - 3.1.407
  - 5.0.201

language: csharp

os: 
  - linux
  - osx
  
# Run the build script
script:
    dotnet restore
    travis_retry dotnet restore Cronos.sln --disable-parallel;
    dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:netcoreapp2.1;
