# Travis-CI Build for Cronos
# see travis-ci.org for details

sudo: required
dist: trusty

language: csharp

os: 
  - linux
  - osx

jobs:
  include:
    - dotnet: 2.1.401
      mono: none
      script:
        travis_retry dotnet restore Cronos.sln --disable-parallel;
        dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:netcoreapp2.1;
    - dotnet: none
      mono: latest
      script:
        travis_retry dotnet restore Cronos.sln --disable-parallel;
        dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:net452;
